theme: jekyll-theme-leap-day
title: "Windows 93 Docs"
description: "A documentation of Windows 93"
show_downloads: false

plugins:
  - jemoji
  - jekyll-mentions
  - jekyll-sitemap
  - jekyll-seo-tag
