theme: jekyll-theme-leap-day
title: "Windows 93 JavaScript Documentation"
description: "A documentation of Windows 93's JavaScript"
show_downloads: false

plugins:
  - jemoji
  - jekyll-mentions
  - jekyll-sitemap
  - jekyll-seo-tag
